services:
  - type: web
    name: ynsocial-backend
    env: php
    plan: free
    rootDirectory: ynsocial.com/httpdocs
    buildCommand: |
      rm -f composer.lock
      composer install --optimize-autoloader --no-dev
      composer require jenssegers/mongodb:^3.9 --no-interaction --no-progress
      composer dump-autoload --optimize
      npm install
      npm run build
      php artisan clear-compiled
      php artisan optimize
      php artisan storage:link
      chmod -R 775 storage bootstrap/cache
    startCommand: "php artisan serve --host=0.0.0.0 --port=${PORT}"
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: "YN Social"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://ynsocial-com-ai.onrender.com
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        value: mongodb+srv://ynsocial:Graf2021@ynsocial.mp9eb.mongodb.net/ynsocial?retryWrites=true&w=majority&appName=ynsocial
      - key: MONGODB_DATABASE
        value: ynsocial
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: noreply@ynsocial.com
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: noreply@ynsocial.com
      - key: MAIL_FROM_NAME
        value: "YN Social"
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: SERVER_PORT
        value: ${PORT}
    autoDeploy: true
